### ISSUE TITLE
Unable to reject requests in local interceptors

### ISSUE THREAD

**Issue by davihsg** [zimicjs/zimic#385]
[UnhandledRequestStrategy](https://github.com/zimicjs/zimic/blob/canary/packages/zimic/src/interceptor/http/interceptor/types/options.ts#L72C1-L72C112) type is defined as:

```ts
export type UnhandledRequestStrategy = UnhandledRequestStrategy.Declaration | UnhandledRequestStrategy.Handler;
```

It should also support other types such as [HandlerContext](https://github.com/zimicjs/zimic/blob/canary/packages/zimic/src/interceptor/http/interceptor/types/options.ts#L36) and [Action](https://github.com/zimicjs/zimic/blob/canary/packages/zimic/src/interceptor/http/interceptor/types/options.ts#L69).

If I create an interceptor passing the parameter `onUnhandledRequest: 'reject'`, ~it rejects requests matching the baseURL as expected~, but type checking fails:

```
❯ npm run types:check

> app-delivery@0.0.1 types:check
> tsc --noEmit

tests/shipping.test.ts:52:3 - error TS2769: No overload matches this call.
  Overload 3 of 3, '(options: HttpInterceptorOptions): LocalHttpInterceptor<ConvertToStrictHttpSchema<ConvertToStrictHttpSchema<{ '/cities': { GET: { request: { searchParams: { query: string; }; }; response: { 200: { body: LocationCity[]; }; 500: { ...; }; }; }; }; '/cities/distances': { ...; }; }>>> | RemoteHttpInterceptor<...>', gave the following error.
    Type 'string' is not assignable to type 'UnhandledRequestStrategy | undefined'.

52   onUnhandledRequest: 'reject',
     ~~~~~~~~~~~~~~~~~~

  node_modules/zimic/dist/interceptor/http.d.ts:411:5
    411     onUnhandledRequest?: UnhandledRequestStrategy;
            ~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'onUnhandledRequest' which is declared here on type 'HttpInterceptorOptions'
 ```

**Comment by diego-aquino** [comment]
Hi, @davihsg!

This behavior is expected, as detailed in [Unhandled requests](https://github.com/zimicjs/zimic/wiki/api%E2%80%90zimic%E2%80%90interceptor%E2%80%90http#unhandled-requests):

> In a [local interceptor](https://github.com/zimicjs/zimic/wiki/getting%E2%80%90started#local-http-interceptors), unhandled requests are always bypassed, meaning that they pass through the interceptor and reach the real network. [Remote interceptors](https://github.com/zimicjs/zimic/wiki/getting%E2%80%90started#remote-http-interceptors) in pair with an [interceptor server](https://github.com/zimicjs/zimic/wiki/cli%E2%80%90zimic%E2%80%90server) always reject unhandled requests because they cannot be bypassed.

In summary, local interceptors **always bypass** unhandled requests, whereas remote interceptors **always reject** them. Currently, you cannot customize that behavior. However, you can still decide whether you want to process the unhandled requests, such as ignore requests to `localhost` and log any others to the console.

There are more explanations and examples in the wiki: https://github.com/zimicjs/zimic/wiki/api%E2%80%90zimic%E2%80%90interceptor%E2%80%90http#unhandled-requests

Let me know if your issue is resolved.

**Comment by davihsg** [comment]
I thought having `onUnhandledRequest: 'reject'` was doing the job, when in fact it wasn't - my mistake then. Is there a way of doing this with a local interceptor?

**Comment by diego-aquino** [comment]
No. Currently, local interceptors always bypass requests. They use an interceptor algorithm to handle requests before they leave the application. Since there's no real server is involved, they don't reject unhandled requests 

This behavior also happens in [MSW](https://mswjs.io/). Despite having `onUnhandledRequest: 'error'` ([learn more](https://mswjs.io/docs/api/setup-server/listen#onunhandledrequest)) on a server or worker, the request still reaches the real network. In that case, "error" means "log the unhandled request to the console as an error".

**Comment by davihsg** [comment]
nice! thanks a lot @diego-aquino!
